import { encodePattern, encodeColorTable } from './pattern.js';

// MSX-BASIC export (FUNCTIONAL_SPEC.md §7, §11, §12.3): DATA statements
// for each grid's pattern + color/attribute bytes (same encoders as
// C/BIN export, so identical byte-for-byte), formatted like
// References/File_Formats/tinysprite.bas, plus a minimal loader.
//
// Loader design: rather than manually computing VDP register values
// and VRAM addresses for the pattern generator / sprite attribute /
// sprite color tables (underspecified in the reference material for
// MSX2's 128KB-VRAM addressing — the sample's own loader was left an
// explicit stub, "MSX2 LOADER NOT YET IMPLEMENTED"), this uses
// MSX-BASIC's native sprite statements, which map onto exactly the
// same hardware tables our bytes encode and let BASIC own table
// placement:
//   - `SPRITE$(pattern#) = <8 bytes>` writes one 8x8 cell of the
//     sprite pattern generator table. A 16x16 sprite is 4 consecutive
//     pattern numbers in our exact quadrant order (§11.1): TL, BL, TR,
//     BR — pattern# = grid_index*4 + {0,1,2,3}.
//   - `COLOR SPRITE$(plane) = <16 bytes>` writes one plane's 16-byte
//     sprite color table entry, byte-for-byte our
//     EC|CC|IC|0|color format (§11.2) — plane = grid_index.
//   - `PUT SPRITE plane,(x,y),,pattern#` places a plane; the omitted
//     color argument leaves the COLOR SPRITE$ table already written in
//     effect (Sprite Mode 2 default), rather than overriding it.
// SCREEN 5 is the smallest MSX2 bitmap mode and defaults to sprite
// mode 2.

const ORIGIN_X = 32;
const ORIGIN_Y = 32;
const TERMINATOR_Y = 216; // hardware sentinel: stop rendering further planes (§11.3)

function formatDataBytes(bytes, perLine = 16) {
  const lines = [];
  for (let i = 0; i < bytes.length; i += perLine) {
    const chunk = Array.from(bytes.slice(i, i + perLine)).map((b) =>
      b.toString(16).padStart(2, '0').toUpperCase()
    );
    lines.push('DATA ' + chunk.join(','));
  }
  return lines;
}

export function exportBasic(project) {
  const grids = project.grids;

  let minX = Infinity;
  let minY = Infinity;
  grids.forEach((sprite) => {
    minX = Math.min(minX, sprite.x);
    minY = Math.min(minY, sprite.y);
  });
  if (!isFinite(minX)) { minX = 0; minY = 0; }

  const lines = [];
  let n = 10;
  const emit = (text) => { lines.push(`${n} ${text}`); n += 10; };

  emit("' Generated by MSX2 Mode 2 Sprite Editor");
  emit("' Loads and displays this project's sprites on a real/emulated MSX2.");
  emit('SCREEN 5');
  emit('COLOR 15,1,1');

  let blockLine = 1000;
  grids.forEach((sprite, i) => {
    n = blockLine;
    const screenX = ORIGIN_X + (sprite.x - minX);
    const screenY = ORIGIN_Y + (sprite.y - minY);
    emit(`' --- Grid ${i} (OR=${sprite.orMode ? 1 : 0}, X=${screenX}, Y=${screenY}) ---`);
    formatDataBytes(encodePattern(sprite)).forEach((d) => emit(d));
    formatDataBytes(encodeColorTable(sprite)).forEach((d) => emit(d));
    emit(`N=32:GOSUB 9000:P=${i * 4}:SPRITE$(P)=MID$(A$,1,8):SPRITE$(P+1)=MID$(A$,9,8):SPRITE$(P+2)=MID$(A$,17,8):SPRITE$(P+3)=MID$(A$,25,8)`);
    emit(`N=16:GOSUB 9000:COLOR SPRITE$(${i})=A$`);
    emit(`PUT SPRITE ${i},(${screenX},${screenY}),,P`);
    blockLine += 100;
  });

  n = 8000;
  emit(`PUT SPRITE ${grids.length},(0,${TERMINATOR_Y})`);
  const haltLine = n;
  emit(`GOTO ${haltLine}`);

  n = 9000;
  emit('A$="":FOR B=1 TO N:READ D$:A$=A$+CHR$(VAL("&H"+D$)):NEXT B:RETURN');

  return lines.join('\n') + '\n';
}
