import { encodePattern, encodeColorTable } from './pattern.js';

function formatBytes(bytes, perLine = 8) {
  const lines = [];
  for (let i = 0; i < bytes.length; i += perLine) {
    const chunk = Array.from(bytes.slice(i, i + perLine)).map(
      (b) => '0x' + b.toString(16).padStart(2, '0').toUpperCase()
    );
    lines.push('  ' + chunk.join(','));
  }
  return lines.join(',\n');
}

// A .c text file with sprite_patterns[]/sprite_attributes[] arrays —
// same byte layout as References/File_Formats/tinysprite.c, concatenated
// across all of the project's grids in left-to-right (plane priority)
// order, per FUNCTIONAL_SPEC.md §7.
export function exportC(project) {
  const patternBlocks = project.grids.map(
    (sprite, i) => `  /* grid ${i} */\n${formatBytes(encodePattern(sprite))}`
  );
  const attrBlocks = project.grids.map(
    (sprite, i) => `  /* grid ${i} */\n${formatBytes(encodeColorTable(sprite))}`
  );
  return (
    `// Generated by MSX2 Mode 2 Sprite Editor\n\n` +
    `unsigned char sprite_patterns[] = {\n${patternBlocks.join(',\n')}\n};\n\n` +
    `unsigned char sprite_attributes[] = {\n${attrBlocks.join(',\n')}\n};\n`
  );
}
